<a href="https://colab.research.google.com/github/sreyajoga4-stack/SREYA-JOGA/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1: Install & Import Libraries

In [1]:
import pandas as pd

Step 2: Upload Dataset in Colab

In [2]:
from google.colab import files
uploaded = files.upload()

Saving dataset.xlsx to dataset.xlsx

Step 3: Load the Dataset

In [7]:
df = pd.read_excel("/content/dataset.xlsx")  # use your file name

Step 4: View Data

In [8]:
df.head()

,OrderID,CustomerName,Email,City,Product,Category,Quantity,Price,OrderDate
0,1018,Amit Shah,amit@gmail.com,Ahmedabad,Laptop,Electronics,1,52000,18-01-2024
1,1014,Anita Sharma,anita@gmail.com,Bangalore,Laptop,Electronics,1,55000,15-01-2024
2,1003,Ravi Kumar,ravi@gmail.com,Delhi,Headphones,Electronics,2,2000,07-01-2024
3,1011,Ravi Kumar,ravi@gmail.com,Delhi,Headphones,Electronics,1,2000,07-01-2024
4,1015,Rahul Verma,rahul@gmail.com,Delhi,Mobile,Electronics,1,28000,18-01-2024

Step 5: Check Duplicate Rows

In [9]:
duplicates = df.duplicated()
print(duplicates.sum())   # number of duplicate rows

0

Step 6: Remove Duplicate Values

In [10]:
df_cleaned = df.drop_duplicates()

Remove duplicates based on specific columns

In [11]:
df_cleaned = df.drop_duplicates(subset=["CustomerName", "Product", "OrderDate"])

Step 7: Keep First / Last Record

In [12]:
# keep first occurrence (default)
df_cleaned = df.drop_duplicates(keep='first')

# keep last occurrence
df_cleaned = df.drop_duplicates(keep='last')

Step 8: Save Cleaned Dataset

In [13]:
df_cleaned.to_csv("cleaned_online_retail.csv", index=False)

Step 9: Download File

In [14]:
files.download("cleaned_online_retail.csv")

In [15]:
df_cleaned = df.drop_duplicates(subset=["CustomerName", "Email", "Product", "OrderDate"])

Handle Missing Values

In [17]:
df.isnull().sum()

OrderID         0
CustomerName    0
Email           0
City            0
Product         0
Category        0
Quantity        0
Price           0
OrderDate       0
dtype: int64

In [18]:
df["CustomerName"].fillna("Unknown", inplace=True)

/tmp/ipykernel_20741/277922612.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["CustomerName"].fillna("Unknown", inplace=True)

In [19]:
df["Email"].fillna("noemail@gmail.com", inplace=True)

/tmp/ipykernel_20741/2641501903.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Email"].fillna("noemail@gmail.com", inplace=True)

In [20]:
df.dropna(subset=["OrderID", "Product"], inplace=True)

Remove Duplicates

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df.drop_duplicates(subset=["CustomerName", "Product", "OrderDate"], inplace=True)

Standardize Text (Data Formatting)

In [23]:
df["CustomerName"] = df["CustomerName"].str.upper()

In [24]:
df["City"] = df["City"].str.title()

In [25]:
df["Email"] = df["Email"].str.lower()

Convert Data Types

In [26]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors='coerce')

/tmp/ipykernel_20741/262411722.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors='coerce')

Handle Incorrect / Invalid Values

In [27]:
df = df[df["Quantity"] > 0]

In [28]:
df = df[df["Price"] > 0]

Save Cleaned Data

In [29]:
df.to_csv("cleaned_online_retail.csv", index=False)